### ISSUE TITLE
How can I get the content

### ISSUE THREAD

**Issue by krismorte** [jsunsoftware/http-request#1]
I'm reading the wiki but not found how to get the content of the request

**Comment by jsunsoftware** [comment]
In the documentation has an answer

Perform simple http request Perform request and get the body of the response without deserialization.

```java
HttpRequest<String> httpRequest = HttpRequestBuilder.create(someHttpMethod, "https://www.jsunsoft.com/", String.class)
                                                .responseDeserializer(ResponseDeserializer.ignorableDeserializer()).build();
String responseBody = httpRequest.execute().get(); // see javadoc of get method
```
Or when you want to convert the body to specific type you can find it in the documentation: convert response body to Generic class
